name: Deadlock Detection (Kani)

on: [pull_request]

jobs:
  kani-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y -qq protobuf-compiler

      - name: Run Kani
        uses: model-checking/kani-github-action@v1
        with:
          args: --no-default-features --features deadlock_detection
